language: node_js
node_js:
  - 7
  - 6
  - 4
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-babel-boilerplate' ]; then cd .. && eval "mv $currentfolder generator-babel-boilerplate" && cd generator-babel-boilerplate; fi
