git:
  depth: 10
sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - '7'
  - '6'
  - '4'

env:
  - JOB=test

script:
  - 'if [ "$JOB" = "test" ]; then make test-ci; fi'
  - 'if [ "$JOB" = "lint" ]; then make lint; fi'

matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: JOB=lint
