language: node_js
node_js:
  - "node"
before_install:
  - 'nvm install-latest-npm'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint ; fi'
  - 'if [ -n "${POSTTEST-}" ]; then npm run posttest ; fi'
  - 'if [ -n "${COVERAGE-}" ]; then npm run coverage ; fi'
  - 'if [ -n "${TEST-}" ]; then npm run tests-only ; elif [ -n "${NATIVE-}" ]; then npm run test:finally:native; fi'
sudo: false
env:
  - TEST=true
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: TEST=true
    - node_js: "9"
      env: NATIVE=true
    - node_js: "8"
      env: NATIVE=true
    - node_js: "8.5"
      env: NATIVE=true
  allow_failures:
