name: Build and Publish Image

on:
  workflow_dispatch: # allows us to trigger runs manually in the GitHub UI
  schedule:
    - cron:  '0 0 * * *' # runs nightly

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with: # these are defined in the GitHub Secrets UI
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nodejs/devcontainer:nightly
