sudo: false
language: node_js
node_js:
  - node
script:
  - npm run build &&
      { [ "@$TRAVIS_BRANCH" = "@master" ] || exit 0; } &&
      $(npm bin)/set-up-ssh
        --key "$encrypted_8dd0e096afa0_key"
        --iv "$encrypted_8dd0e096afa0_iv"
        --path-encrypted-key ".travis-github-deploy-key.enc" &&
      git checkout "$TRAVIS_BRANCH" &&
      git add docs &&
      {
        git diff --staged --stat &&
        git commit --no-verify -m "Generated content @ $TRAVIS_COMMIT [skip ci]" ||
        exit 0;
      } &&
      git push "git@github.com:${TRAVIS_REPO_SLUG}.git" HEAD

git:
  depth: 1
