name: 'build & lint ecmarkup'

on: [pull_request, push]

jobs:
  build:
    name: 'build & lint ecmarkup'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run build
