language: node_js
after_success:
  - $(npm bin)/set-up-ssh --key "${encrypted_4a611c0bc0a9_key}"
      --iv "${encrypted_4a611c0bc0a9_iv}"
      --path-encrypted-key .travis-github-deploy-key.enc
  - $(npm bin)/update-branch --commands 'npm run build'
      --commit-message "Update gh-pages @ ${TRAVIS_COMMIT}"
      --directory 'dist'
      --distribution-branch 'gh-pages'
      --source-branch 'master'
git:
  depth: 1
branches:
  only:
    - master
env:
  global:
    secure: "NVGrQwyxrNOJewYlu2t8Hz1RSNEITth2dKa/16flSqxrkAOk6hSZPHWFhGPSGMPfB+Q6LV9E5Fyf9ffbx/k9KPCsH6wbYZIk9nrBva6kDW6ZLCGAeYKHDX0pQMaeuRTIvEgFD/5dwf03UhfKZLqlDkLkzf/teqKMxPIPG9+C+8SrAzznGSN4IZxJV17z3AJ53czydeGc7DvvHwF2YDeWC8LadvP7eZhHYZ8oP1FL9ajx8q5k9WtN2Mf86ypMwulM9Oj7jz9gOOw5VghCqZH+EIzMZw4/GgIHguEk+ANVkauwQIbQK82L1HuGfzNHz/JAl2d3eFc1tkiVDRA+WNK0nrMWC81v4TceRXLzqlU76ck1QX7DlpxGAFREvgbz6nyl+A3pN/4SNISYgrR9nqVlsFmMIuLivcIS8pShhJxPNrQ3gNGfUw42TIy0e63n4o+jpgDQkMHSM8wx8W57RQKCLKHPo6tPNlZJjGH0FMXYyQQN0PMacrjazm07tR8+zRTle6lCASHsDAyPZwQJDAVA8mJf00RokUsTFW3UbtIkxTBQmJYii7WH4vKabgyeY4IkpKkQ1h811j4tyoBpyzYc7SvcGWWCNzePLVRUuUqRyXdX3FsHWVOIKTAZAPx7Ezqaf5uBwMA3UOqtHOnyA/1m+8pSgwGlzLG5BHlwYBmyFA0="
