name: Update LKG

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Release branch name to LKG
        required: true
        type: string

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ ! "${{ inputs.branch_name }}" =~ ^release- ]]; then
            echo "Branch name must start with 'release-'"
            exit 1
          fi

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.branch_name }}
          token: ${{ secrets.TS_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 'lts/*'
      - run: |
          npm --version
          # corepack enable npm
          npm install -g $(jq -r '.packageManager' < package.json)
          npm --version
      - run: |
          npm ci
          npx hereby LKG
          git add --force ./lib
          git config user.email "typescriptbot@microsoft.com"
          git config user.name "TypeScript Bot"
          git commit -m 'Update LKG'
          git push
