language: node_js
node_js:
  - '8'
script:
  - npm run build
deploy:
  local_dir: dist
  email: mathias@qiwi.be
  name: Mathias Bynens
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

