sudo: off

language: node_js

node_js:
  - stable

script:
  - bash ./deploy.sh

env:
  global:
    - ENCRYPTION_LABEL: "856fa5c47e24"
    - GH_USER_NAME: "littledan"
    - GH_USER_EMAIL: "littledan@igalia.com"
    - PRIVATE_KEY_FILE_NAME: "github_deploy_key.enc"
