language: ruby
cache: bundler
install:
- script/rebund download
- bundle install --path vendor/bundle
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
script: script/cibuild
after_script:
- script/rebund upload
notifications:
  # irc:
  #   on_success: change
  #   on_failure: change
  #   channels:
  #   - irc.freenode.org#jekyll
  #   template:
  #   - '%{repository}#%{build_number} (%{branch}) %{message} %{build_url}'
  # email:
  #   on_success: never
  #   on_failure: never
env:
  global:
